### ISSUE TITLE
Docker latest image bug

### ISSUE THREAD

**Issue by i-d-c-p** [devopsfaith/krakend#438]
**Describe the bug**
I tried to run krakend using docker with the latest image and it shows the next error:

```
2020/12/17 16:29:44  DEBUG: lua: no extra config
panic: runtime error: index out of range [0] with length 0
```

**To Reproduce**
1. Create a configuration file as follows:
```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "INFO",
      "prefix": "[KRAKEND]",
      "syslog": true,
      "stdout": true,
      "format": "custom",
      "custom_format": "%{message}"
    }
  },
  "plugin": {
    "pattern":".so",
    "folder": "./plugin/"
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Gateway:0.0.1",
  "endpoints": [
    {
      "endpoint": "/auth/refreshToken",
      "method": "GET",
      "output_encoding": "json",
      "headers_to_pass": [
        "my-header"
      ],
      "backend": [
        {
          "url_pattern": "/auth/refreshToken",
          "encoding": "json",
          "sd": "dns",
          "method": "GET",
          "extra_config": {
            "github_com/devopsfaith/krakend/transport/http/client/executor": {
              "name": "RBAC-checker"
            }
          }
        }
      ]
    }
  ]
}
```
2. Run krakend inside docker using 
`docker run -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend run --config /etc/krakend/krakend.json `

**Expected behavior**
Krakend running as expected

**Logs**
```Parsing configuration file: /etc/krakend/krakend.json
2020/12/17 16:29:44  ERROR: unable to create the gologging logger: Unix syslog delivery error
2020/12/17 16:29:44  ERROR: unable to create the GELF writer: getting the extra config for the krakend-gelf module
2020/12/17 16:29:44  INFO: Listening on port: 8080
2020/12/17 16:29:44  INFO: total http executor plugins loaded: 0
2020/12/17 16:29:44  INFO: total http handler plugins loaded: 0
2020/12/17 16:29:44  DEBUG: creating a new influxdb client
2020/12/17 16:29:44  DEBUG: no config for the influxdb client. Aborting
2020/12/17 16:29:44  WARNING: influxdb: unable to load custom config
2020/12/17 16:29:44  WARNING: opencensus: no extra config defined for the opencensus module
2020/12/17 16:29:44  WARNING: building the etcd client: unable to create the etcd client: no config
2020/12/17 16:29:44  INFO: registering usage stats for cluster ID '5JkNZIy8Oiz9n0/Aud11hZ18jF15jbZcxFwe+F60yFU='
2020/12/17 16:29:44  DEBUG: no config for the bloomfilter
2020/12/17 16:29:44  WARNING: bloomFilter: no config for the bloomfilter
2020/12/17 16:29:44  WARNING: no config present for the httpsecure module
2020/12/17 16:29:44  DEBUG: lua: no extra config
2020/12/17 16:29:44  DEBUG: botdetector middleware:  no config defined for the module
2020/12/17 16:29:44  DEBUG: http-request-executor: no extra config for backend /auth/refreshToken
2020/12/17 16:29:44  DEBUG: CEL: no extra config detected for backend /auth/refreshToken
2020/12/17 16:29:44  DEBUG: lua: no extra config
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/devopsfaith/krakend/sd/dnssrv.SubscriberFactory(0xc00071e140, 0xc0000ad130, 0x3)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/sd/dnssrv/subscriber.go:31 +0x85
github.com/devopsfaith/krakend/sd.GetSubscriber(0xc00071e140, 0xc00059e860, 0x8)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/sd/register.go:17 +0x5d
github.com/devopsfaith/krakend/proxy.defaultFactory.newStack(0xc00059e620, 0x2748f20, 0xc000364a40, 0x2537c40, 0xc00071e140, 0xdc1e8f)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:86 +0x51
github.com/devopsfaith/krakend/proxy.defaultFactory.newSingle(...)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:81
github.com/devopsfaith/krakend/proxy.defaultFactory.New(0xc00059e620, 0x2748f20, 0xc000364a40, 0x2537c40, 0xc0007140a0, 0x2105500, 0xc000498020, 0xc0007bee50)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:58 +0x165
github.com/devopsfaith/krakend/proxy.shadowFactory.New(0x2704b20, 0xc00059e640, 0xc0007140a0, 0xe43f45, 0xc0007bef98, 0x0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/shadow.go:38 +0x355
github.com/devopsfaith/krakend-jsonschema.ProxyFactory.func1(0xc0007140a0, 0xc0007bef90, 0xdb4a85, 0xc000000180)
        /go/pkg/mod/github.com/devopsfaith/krakend-jsonschema@v0.0.0-20200611142303-11a34c8149c3/jsonschema.go:26 +0x3d
github.com/devopsfaith/krakend/proxy.FactoryFunc.New(0xc00059e660, 0xc0007140a0, 0xdd177b, 0xdcf27a, 0x1)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:23 +0x30
github.com/devopsfaith/krakend-cel.ProxyFactory.func1(0xc0007140a0, 0x7fa16178c768, 0x3f, 0xe2cbf2)
        /go/pkg/mod/github.com/devopsfaith/krakend-cel@v0.0.0-20200908134208-7162c125376d/proxy.go:17 +0x63
github.com/devopsfaith/krakend/proxy.FactoryFunc.New(0xc0007221b0, 0xc0007140a0, 0x7fa1617837d0, 0xc0000c0005, 0xc0000423f0)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:23 +0x30
github.com/devopsfaith/krakend-lua/proxy.ProxyFactory.func1(0xc0007140a0, 0x39, 0x8, 0xc000042400)
        /go/pkg/mod/github.com/devopsfaith/krakend-lua@v1.1.2-0.20200909152058-1b4e6c9afb8f/proxy/proxy.go:21 +0x69
github.com/devopsfaith/krakend/proxy.FactoryFunc.New(0xc0007221e0, 0xc0007140a0, 0x68, 0x23ad6a0, 0xd58e90)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:23 +0x30
github.com/devopsfaith/krakend/proxy.FactoryFunc.New(0xc00059e6a0, 0xc0007140a0, 0xc0000423f0, 0xb, 0x18)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:23 +0x30
github.com/devopsfaith/krakend/proxy.FactoryFunc.New(0xc00059e6c0, 0xc0007140a0, 0x9, 0xc00059e780, 0x3)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/proxy/factory.go:23 +0x30
github.com/devopsfaith/krakend/router/gin.ginRouter.registerKrakendEndpoints(0xc0000e4140, 0x0, 0x0, 0x0, 0xc00059e740, 0x2704b00, 0xc00059e6c0, 0x2748f20, 0xc000364a40, 0xc00059e760, ...)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/router/gin/router.go:109 +0x8b
github.com/devopsfaith/krakend/router/gin.ginRouter.Run(0xc0000e4140, 0x0, 0x0, 0x0, 0xc00059e740, 0x2704b00, 0xc00059e6c0, 0x2748f20, 0xc000364a40, 0xc00059e760, ...)
        /go/pkg/mod/github.com/devopsfaith/krakend@v1.1.2-0.20200930142252-7c9d4ace4128/router/gin/router.go:94 +0x1e7
github.com/devopsfaith/krakend-ce.(*ExecutorBuilder).NewCmdExecutor.func1(0xc0000ace30, 0xd, 0xc0004980e0, 0x1, 0x1, 0xb2d05e00, 0x45d964b800, 0x33f67e0, 0x0, 0x0, ...)
        /app/executor.go:170 +0x7b7
github.com/devopsfaith/krakend-cobra.runFunc(0x329e020, 0xc000490400, 0x0, 0x2)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v0.0.0-20200317174411-3518505e8cd2/run.go:24 +0x19f
github.com/spf13/cobra.(*Command).execute(0x329e020, 0xc0004903a0, 0x2, 0x2, 0x329e020, 0xc0004903a0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x329db20, 0xd597f8, 0x20, 0x228fee0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/devopsfaith/krakend-cobra.Execute(0x2704ac0, 0xc0003e8d00, 0xc000490280)
        /go/pkg/mod/github.com/devopsfaith/krakend-cobra@v0.0.0-20200317174411-3518505e8cd2/cmd.go:20 +0x65
main.main()
        /app/cmd/krakend-ce/main.go:56 +0x365
```

**Additional context**
Docker community desktop for Mac, version 3.0.1

**Comment by kpacha** [comment]
your config does not define a backend host. check this out for more details: https://www.krakend.io/docs/service-discovery/dns-srv/
